USE [master]
GO

/****** Object:  Database [StatKeeper]    Script Date: 1/4/2018 5:20:54 PM ******/
IF DB_ID('StatKeeper') IS NOT NULL DROP DATABASE [StatKeeper]
GO

/****** Object:  Database [StatKeeper]    Script Date: 1/4/2018 5:20:54 PM ******/
CREATE DATABASE [StatKeeper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StatKeeper', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\StatKeeper.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StatKeeper_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\StatKeeper_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StatKeeper] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StatKeeper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StatKeeper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StatKeeper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StatKeeper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StatKeeper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StatKeeper] SET ARITHABORT OFF 
GO

ALTER DATABASE [StatKeeper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StatKeeper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StatKeeper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StatKeeper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StatKeeper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StatKeeper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StatKeeper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StatKeeper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StatKeeper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StatKeeper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StatKeeper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StatKeeper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StatKeeper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StatKeeper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StatKeeper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StatKeeper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StatKeeper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StatKeeper] SET RECOVERY FULL 
GO

ALTER DATABASE [StatKeeper] SET  MULTI_USER 
GO

ALTER DATABASE [StatKeeper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StatKeeper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StatKeeper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StatKeeper] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [StatKeeper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StatKeeper] SET  READ_WRITE 
GO


